# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-16 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=100)),
                ('code_certification', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_calibration', models.PositiveIntegerField()),
                ('due_calibration', models.DateField()),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.Instrument')),
            ],
        ),
    ]
