# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-16 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluation', '0001_initial'),
        ('company', '0002_miningunit_customer'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('code_area', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=60)),
                ('agent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluation.AgentCategory')),
                ('mining_init', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.MiningUnit')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observations', models.TextField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('consulting_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.ConsultingCompany')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='StatusProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.StatusProject'),
        ),
        migrations.AddField(
            model_name='detailproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
