# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_statusproject_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailproject',
            name='agent_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_category_detail_project', to='evaluation.AgentCategory'),
        ),
        migrations.AlterField(
            model_name='detailproject',
            name='mining_init',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mining_init_detail_project', to='company.MiningUnit'),
        ),
        migrations.AlterField(
            model_name='detailproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_detail_project', to='project.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='consulting_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulting_company_project', to='company.ConsultingCompany'),
        ),
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_project', to='customer.Customer'),
        ),
    ]
