# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_miningunit_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miningunit',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_mining_unit', to='customer.Customer'),
        ),
    ]
